name: CI-CD ProAudit

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, gd, zip, mysql, sqlite
        
    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Prepare Laravel
      run: |
        cp .env.example .env
        php artisan key:generate
        
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      
# name: CI-CD ProAudit

# on:
#   push:
#     branches: [ "main", "develop" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   laravel-tests:
#     runs-on: ubuntu-latest

#     services:
#         mysql:
#             image: mysql:8.0
#             env:
#             MYSQL_ROOT_PASSWORD: password
#             MYSQL_DATABASE: proaudit_test
#             ports:
#             - 3306:3306
#             options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#     steps:
#     - uses: actions/checkout@v4

#     - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#             php-version: '8.2' # Aseg√∫rate que coincida con tu composer.json
#             extensions: mbstring, dom, curl, libxml, mysql
#             coverage: xdebug

#     - name: Install Dependencies
#         run: |
#         composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
#         cp .env.example .env
#         php artisan key:generate

#     - name: Install NPM Dependencies & Build
#         run: |
#         npm install
#         npm run build

#     - name: Directory Permissions
#         run: chmod -R 777 storage bootstrap/cache

#     - name: Execute Tests (PHPUnit)
#         env:
#         DB_CONNECTION: mysql
#         DB_HOST: 127.0.0.1
#         DB_PORT: 3306
#         DB_DATABASE: proaudit_test
#         DB_USERNAME: root
#         DB_PASSWORD: password
#         run: php artisan test

